app_frontend:
    resource: "@AppBundle/Resources/config/routing/frontend.yml"
    prefix: /

app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml"
    prefix: /users

app_products:
    resource: "@AppBundle/Resources/config/routing/products.yml"
    prefix: /products

app_categories:
    resource: "@AppBundle/Resources/config/routing/categories.yml"
    prefix: /categories