# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

#    role_hierarchy:
#        #Con la linea de abajo, el ROL_ADMINISTRADOR podra acceder a los permisos de ROL COMERCIAL
#        ROLE_ADMINISTRADOR: ROLE_COMERCIAL
#        ROLE_SUPER_ADMINISTRADOR: [ ROLE_ADMINISTRADOR, ROLE_ALLOWED_TO_SWITCH ]
#    
#    access_control:
#    #ACCESO PARA ADMINISTRADOR
#        - { path: ^/users/list, roles: ROLE_ADMINISTRADOR}
#        - { path: ^/users/create, roles: ROLE_ADMINISTRADOR}
#        - { path: ^/users/delete, roles: ROLE_ADMINISTRADOR}
#    #NO AUTENTICADOS
#        - { path: ^/users/update, roles: ROLE_COMERCIAL}
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}