inicio:
    path:      /
    defaults:  { _controller: AppBundle:Frontend:index}

login:
    path:      /login
    defaults:  { _controller: AppBundle:Frontend:login}

login_check:
    path:      /login_check

logout:
    path:      /logout